name: CI

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Check if contract ABIs are compatible
        run: yarn check-abi

      - name: Build dev-frontend Docker image
        if: ${{ github.event_name == 'push' }}
        run: |
          docker-compose build
          docker-compose push
        working-directory: ./packages/dev-frontend

      - name: Build dev-frontend for internal use
        run: yarn build
        env:
          CHANNEL: internal

      - name: Check if contract ABIs are compatible on internal channel
        run: yarn check-abi

      - name: Build dev-frontend Docker image for internal use
        if: ${{ github.event_name == 'push' }}
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.internal.yml build
          docker-compose -f docker-compose.yml -f docker-compose.internal.yml push
        working-directory: ./packages/dev-frontend
